// Mocks generated by Mockito 5.4.5 from annotations
// in luna_authoring_system/test/odp_tree_compiler/odp_tree_builder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:luna_authoring_system/pptx_tree_compiler/pptx_xml_to_json_converter.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PptxXmlToJsonConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPptxXmlToJsonConverter extends _i1.Mock
    implements _i2.PptxXmlToJsonConverter {
  @override
  dynamic getJsonFromPptx(String? xmlFilePath) => super.noSuchMethod(
        Invocation.method(
          #getJsonFromPptx,
          [xmlFilePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getTempPath() => (super.noSuchMethod(
        Invocation.method(
          #getTempPath,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getTempPath,
            [],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getTempPath,
            [],
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
