name: luna_mhealth_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  archive: ^3.4.10
  audioplayers: ^5.2.1
  azure_application_insights: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter_image_compress: ^2.1.0
  global_configuration: ^2.0.0
  path_provider: ^2.1.2
  provider: ^6.0.1
  url_launcher: ^6.0.9
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/test_data/
    - assets/cfg/app_settings.json
    - assets/data/
    - assets/JSON_images/slide_1/
    - assets/JSON_images/slide_2/
    - assets/JSON_images/slide_3/
