# Pipeline to run luna integration tests
# This pipeline starts an android emulator and then uses flutter drive to test the mobile application
trigger: none


# macOS-13 was the one of the few vmImages that did not get stuck creating an android emulator for 10 mins. 
pool:
  vmImage: macOS-13

variables:
  - name: package_path
    value: 'luna_mobile'
  - name: driver_path
    value: 'test_driver/drive_integrations.dart'
  - name: test_folder
    value: 'integration_test'

steps:

- template: ../templates/install_prereqs.yml

# Start android emulator
- task: Bash@3
  inputs:
    filePath: ./pipelines/scripts/start_android_emulator.sh
  displayName: 'Start Android emulator'

  # This is a placeholder for later dev to get the most recent build

  # - task: DownloadPipelineArtifact@2
  #   inputs:
  #     source: 'specific'
  #     pipeline: 1234  # ID of the pipeline that produced the artifact
  #     runVersion: 'latest'
  #     artifact: 'your-artifact-name'
  #     path: '$(Build.SourcesDirectory)/downloaded-artifact'
  #   displayName: 'Download Artifact from Another Pipeline'


# Create android flutter project
- script: |
    cd $(package_path)
      flutter clean
      flutter pub get
      flutter create --platforms=android .
  displayName: 'Get Flutter packages for the $(package_path)'

# Run the integration test
# flutter drive does not have a --machine for outputing test results and converting to junit
# Just fail the task if "All tests passed" isn't present
- task: PowerShell@2
  displayName: 'Run $(package_path) tests'
  inputs:
    targetType: 'inline'
    script: |
      cd $(package_path)
      flutter drive --driver=$(driver_path) --target=$(test_folder)/luna_mobile_e2e_test.dart | Tee-Object -FilePath mobile_integration_tests.log
      if (-not (Select-String -Path mobile_integration_tests.log -Pattern "All tests passed")) {
        Write-Host "##vso[task.logissue type=error]Integration Test Failed"
        Write-Host "##vso[task.complete result=Failed]"
        exit 1
      }
