# Build pipeline for luna authoring system
# builds the luna authoring system and zips it up and publishes it as a pipeline artifact. 
# it does this for the the OS's listed in the strategy matrix

trigger: none

strategy:
  matrix:
    mac:
      imageName: 'macOS-latest'
      buildOS: 'macos'
      package_name: 'MacBuild_$(Build.BuildNumber)'
      release_dir: '/Build/Products/Release'
    windows:
      imageName: 'windows-latest'
      buildOS: 'windows'
      package_name: 'WindowsBuild_$(Build.BuildNumber)'
      release_dir: '/x64/runner/Release'

pool:
  vmImage: $(imageName)

variables:
- group: 'Version Numbers' #this is a variable group in the library
- name: 'authoring_path'
  value: 'luna_authoring_system'

name: $(version_numbers_luna_authoring).$(Rev:r) #increment build counter everytime build is run

steps:

- template: templates/install_prereqs.yml
- template: templates/build_authoring_system.yml
  parameters:
    build_os: $(buildOS)
    package_name: $(package_name)
    release_directory: $(release_dir)
    build_name: $(Build.BuildNumber)

# publish built zip files as a pipeline artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(package_name).zip' 
    artifact: "Authoring_System_Build_$(package_name)"
    publishLocation: 'pipeline' 
