// Mocks generated by Mockito 5.4.5 from annotations
// in luna_authoring_system/test/pptx_tree_compiler/slide/pptx_slide_builder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:flutter/rendering.dart' as _i14;
import 'package:luna_authoring_system/pptx_data_objects/connection_shape.dart'
    as _i13;
import 'package:luna_authoring_system/pptx_data_objects/pptx_hierarchy.dart'
    as _i11;
import 'package:luna_authoring_system/pptx_data_objects/shape.dart' as _i9;
import 'package:luna_authoring_system/pptx_data_objects/shape_type.dart'
    as _i15;
import 'package:luna_authoring_system/pptx_data_objects/transform.dart' as _i4;
import 'package:luna_authoring_system/pptx_tree_compiler/connection_shape/pptx_connection_shape_builder.dart'
    as _i12;
import 'package:luna_authoring_system/pptx_tree_compiler/pptx_xml_to_json_converter.dart'
    as _i5;
import 'package:luna_authoring_system/pptx_tree_compiler/relationship/pptx_relationship_parser.dart'
    as _i10;
import 'package:luna_authoring_system/pptx_tree_compiler/shape/pptx_shape_builder.dart'
    as _i8;
import 'package:luna_authoring_system/pptx_tree_compiler/slide_count/pptx_slide_count_parser.dart'
    as _i7;
import 'package:luna_core/units/emu.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEMU_0 extends _i1.SmartFake implements _i2.EMU {
  _FakeEMU_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_1 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransform_2 extends _i1.SmartFake implements _i4.Transform {
  _FakeTransform_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PptxXmlToJsonConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPptxXmlToJsonConverter extends _i1.Mock
    implements _i5.PptxXmlToJsonConverter {
  @override
  dynamic getJsonFromPptx(String? xmlFilePath) => super.noSuchMethod(
        Invocation.method(
          #getJsonFromPptx,
          [xmlFilePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getTempPath() => (super.noSuchMethod(
        Invocation.method(
          #getTempPath,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTempPath,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTempPath,
            [],
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PptxSlideCountParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockPptxSlideCountParser extends _i1.Mock
    implements _i7.PptxSlideCountParser {
  @override
  int get slideCount => (super.noSuchMethod(
        Invocation.getter(#slideCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [PptxShapeBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockPptxShapeBuilder extends _i1.Mock implements _i8.PptxShapeBuilder {
  @override
  List<_i9.Shape> getShapes(Map<String, dynamic>? shapeTree) =>
      (super.noSuchMethod(
        Invocation.method(
          #getShapes,
          [shapeTree],
        ),
        returnValue: <_i9.Shape>[],
        returnValueForMissingStub: <_i9.Shape>[],
      ) as List<_i9.Shape>);
}

/// A class which mocks [PptxRelationshipParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockPptxRelationshipParser extends _i1.Mock
    implements _i10.PptxRelationshipParser {
  @override
  int getParentIndex(
    int? currentIndex,
    _i11.PptxHierarchy? pptxHierarchy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParentIndex,
          [
            currentIndex,
            pptxHierarchy,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [PptxConnectionShapeBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockPptxConnectionShapeBuilder extends _i1.Mock
    implements _i12.PptxConnectionShapeBuilder {
  @override
  List<_i9.Shape> getConnectionShapes(dynamic shapeTree) => (super.noSuchMethod(
        Invocation.method(
          #getConnectionShapes,
          [shapeTree],
        ),
        returnValue: <_i9.Shape>[],
        returnValueForMissingStub: <_i9.Shape>[],
      ) as List<_i9.Shape>);
}

/// A class which mocks [ConnectionShape].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionShape extends _i1.Mock implements _i13.ConnectionShape {
  @override
  _i2.EMU get width => (super.noSuchMethod(
        Invocation.getter(#width),
        returnValue: _FakeEMU_0(
          this,
          Invocation.getter(#width),
        ),
        returnValueForMissingStub: _FakeEMU_0(
          this,
          Invocation.getter(#width),
        ),
      ) as _i2.EMU);

  @override
  set width(_i2.EMU? _width) => super.noSuchMethod(
        Invocation.setter(
          #width,
          _width,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Color get color => (super.noSuchMethod(
        Invocation.getter(#color),
        returnValue: _FakeColor_1(
          this,
          Invocation.getter(#color),
        ),
        returnValueForMissingStub: _FakeColor_1(
          this,
          Invocation.getter(#color),
        ),
      ) as _i3.Color);

  @override
  set color(_i3.Color? _color) => super.noSuchMethod(
        Invocation.setter(
          #color,
          _color,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.BorderStyle get style => (super.noSuchMethod(
        Invocation.getter(#style),
        returnValue: _i14.BorderStyle.none,
        returnValueForMissingStub: _i14.BorderStyle.none,
      ) as _i14.BorderStyle);

  @override
  set style(_i14.BorderStyle? _style) => super.noSuchMethod(
        Invocation.setter(
          #style,
          _style,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Transform get transform => (super.noSuchMethod(
        Invocation.getter(#transform),
        returnValue: _FakeTransform_2(
          this,
          Invocation.getter(#transform),
        ),
        returnValueForMissingStub: _FakeTransform_2(
          this,
          Invocation.getter(#transform),
        ),
      ) as _i4.Transform);

  @override
  set transform(_i4.Transform? _transform) => super.noSuchMethod(
        Invocation.setter(
          #transform,
          _transform,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isFlippedVertically => (super.noSuchMethod(
        Invocation.getter(#isFlippedVertically),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isFlippedVertically(bool? _isFlippedVertically) => super.noSuchMethod(
        Invocation.setter(
          #isFlippedVertically,
          _isFlippedVertically,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.ShapeType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i15.ShapeType.picture,
        returnValueForMissingStub: _i15.ShapeType.picture,
      ) as _i15.ShapeType);
}
