# Pipeline to rubn
trigger: none

pool:
  vmImage: windows-latest

variables:
  - name: package_path
    value: 'luna_mobile'
  - name: driver_path
    value: 'test_driver/drive_integrations.dart'
  - name: test_folder
    value: 'integration_test'

steps:

- template: ../templates/install_prereqs.yml

- template: ../templates/run_luna_authoring.yml
  parameters:
    operating_system: 'windows'


