# Lint and Testing pipeline for Luna mHealth
# YML that gets run when a PR is requested
trigger: none

pool:
  vmImage: windows-latest

variables:
  - name: package_folders
    value: luna_core,luna_authoring_system,luna_mobile

steps:

- template: ../templates/install_prereqs.yml
- template: ../templates/run_luna_authoring
