# Nightly Build for Luna mHealth
# Runs unit tests and then integration tests

trigger: none

jobs:

- job: mactest


  pool:
    vmImage: macos-latest
  variables:
    - name: package_folders
      value: luna_core,luna_authoring_system,luna_mobile

  steps:

  - template: ../templates/install_prereqs.yml


  - template: ../templates/run_luna_authoring.yml
    parameters:
      operating_system: macos