# Build pipeline for luna authoring system
# builds the luna authoring system and zips it up and publishes it as a pipeline artifact. 
# it does this for the the OS's listed in the strategy matrix

trigger: none

jobs:

- job: UpdateVersionNumber
  pool:
    vmImage: 'ubuntu-latest'
  steps:

    - checkout: self
      persistCredentials: true
    - bash: |
        git config --global user.email "pipeline@dev.azure.com"
        git config --global user.name "Azure DevOps Pipeline"
      name: GitConfig

    - template: ../templates/update_version.yml


# - job: BuildLunaAuthoring
#   pool:
#     vmImage: 'ubuntu-latest'

#   variables:
#   - name: 'mobile_path'
#     value: 'luna_mobile'
#   - name: 'build_path'
#     value: 'build/app/outputs/flutter-apk/app-release.apk'
#   - name: 'package_name'
#     value: 'Luna_MobileBuild_$(Build.BuildNumber)'
#   - name: 'version_number'
#     value: $[ dependencies.UpdateVersionNumber.outputs['setVersion.version'] ]
    

#   steps:

#   - template: templates/install_prereqs.yml

#   - template: templates/build_mobile_app.yml
#     parameters:
#       build_name: $(Build.BuildNumber)
#       archive_file: true
#       package_name: $(package_name)

#   - template: templates/upload_file_gdrive.yml
#     parameters:
#       gdrive_id: $(gdrive_id_luna_mobile)
#       package_name: $(package_name)
#       source_dir: $(Build.SourcesDirectory)


# - job: BuildLunaAuthoring

#   strategy:
#     matrix:
#       mac:
#         imageName: 'macOS-latest'
#         buildOS: 'macos'
#         package_name: 'Luna_MacBuild_$(Build.BuildNumber)'
#         release_dir: '/Build/Products/Release'
#         gdrive: $(gdrive_id_mac_build)
#       windows:
#         imageName: 'windows-latest'
#         buildOS: 'windows'
#         package_name: 'Luna_WindowsBuild_$(Build.BuildNumber)'
#         release_dir: '/x64/runner/Release'
#         gdrive: $(gdrive_id_windows_build)

#   pool:
#     vmImage: $(imageName)

#   variables:
#   - group: 'Google Drive IDs'
#   - name: 'authoring_path'
#     value: 'luna_authoring_system'


#   steps:

#   - template: templates/install_prereqs.yml
#   - template: templates/build_authoring_system.yml
#     parameters:
#       build_os: $(buildOS)
#       package_name: $(package_name)
#       release_directory: $(release_dir)
#       build_name: $(Build.BuildNumber)

#   - template: templates/upload_file_gdrive.yml
#     parameters:
#       gdrive_id: $(gdrive)
#       package_name: $(package_name)
#       source_dir: $(Build.SourcesDirectory)